# docker-compose.yml
version: '3'
services:
  mysql-master:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
    ports:
      - "3321:3306"
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    command: >
      --server-id=1
      --log-bin=mysql-bin
    hostname: mysql-master
  mysql-slave:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
    ports:
      - "3322:3306"
    volumes:
      - ./db/mysql/slave/data:/var/lib/mysql
      - ./db/mysql/slave/init:/docker-entrypoint-initdb.d
    command: >
      --server-id=2
      --relay-log=relay-bin
      --log-bin=mysql-bin
      --read-only=1
